// 工位看盘 - 预加载桥
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gongwei', {
  getStore: () => ipcRenderer.invoke('store:get'),
  getVersion: () => ipcRenderer.invoke('app:version'),
  getMarket: () => ipcRenderer.invoke('market:get'),
  refreshMarket: () => ipcRenderer.invoke('market:refresh'),
  search: (keyword) => ipcRenderer.invoke('search', keyword),
  addStock: (item) => ipcRenderer.invoke('stocks:add', item),
  removeStock: (id) => ipcRenderer.invoke('stocks:remove', id),
  updateAlert: (id, alert) => ipcRenderer.invoke('stocks:update-alert', { id, alert }),
  reorderStocks: (ids) => ipcRenderer.invoke('stocks:reorder', ids),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  toggleIndex: (id, on) => ipcRenderer.invoke('indices:toggle', { id, on }),
  reorderIndices: (ids) => ipcRenderer.invoke('indices:reorder', ids),
  toggleFloat: () => ipcRenderer.invoke('float:toggle'),
  hideFloat: () => ipcRenderer.invoke('float:hide'),
  floatResize: (h) => ipcRenderer.send('float:resize', h),
  onFloatSync: (cb) => ipcRenderer.on('float:sync', () => cb()),
  testNotify: () => ipcRenderer.invoke('notify:test'),
  diagnose: () => ipcRenderer.invoke('diagnose'),
  applyProxy: () => ipcRenderer.invoke('proxy:apply'),
  testProxy: () => ipcRenderer.invoke('proxy:test'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  openExternal: (url) => ipcRenderer.invoke('open:external', url),
  onUpdateState: (cb) => ipcRenderer.on('update:state', (_e, data) => cb(data)),
  selftest: () => ipcRenderer.invoke('selftest'),
  getKline: (stock, period, limit) => ipcRenderer.invoke('kline:get', { stock, period, limit }),
  getTrends: (stock) => ipcRenderer.invoke('trends:get', stock),
  getDetail: (stock) => ipcRenderer.invoke('detail:get', stock),
  openChart: (stock) => ipcRenderer.invoke('chart:open', stock),
  getChartStock: () => ipcRenderer.invoke('chart:stock'),
  onChartUpdate: (cb) => ipcRenderer.on('chart:update', (_e, stock) => cb(stock)),
  openAlert: (stock) => ipcRenderer.invoke('alert:open', stock),
  getAlertStock: () => ipcRenderer.invoke('alert:stock'),
  onAlertUpdate: (cb) => ipcRenderer.on('alert:update', (_e, stock) => cb(stock)),
  onMarket: (cb) => ipcRenderer.on('market:update', (_e, data) => cb(data)),
  onSession: (cb) => ipcRenderer.on('session:update', (_e, data) => cb(data)),
  onOpenSettings: (cb) => ipcRenderer.on('ui:open-settings', () => cb()),
  onStore: (cb) => ipcRenderer.on('store:changed', (_e, data) => cb(data)),
  onAlert: (cb) => ipcRenderer.on('alert:trigger', (_e, data) => cb(data)),
});
